#!/bin/sh

mkdir -p /dev /proc /sys

mount -t devtmpfs none /dev/
mount -t proc none /proc/
mount -t sysfs none /sys/

# Enable the loopback device
ip link set lo up
ip addr add 127.0.0.1/8 dev lo 2>/dev/null

ETH_IFACE="${1:-eth0}"
WIFI_IFACE="${2:-wlan0}"
ip link set $ETH_IFACE up
ip link set $WIFI_IFACE up

mkdir -p /usr/local/bin

export PATH=/bin:/sbin:/usr/local/bin:/usr/bin:/usr/sbin
export PYTHONHOME=/usr
export PYTHONPATH=/usr/lib/python3.14:/usr/lib/python3.14/site-packages

ln -s /usr/bin/python3 /usr/local/bin/python3
ln -s /usr/bin/python3 /usr/local/bin/python3.14
ln -s /usr/bin/python3 /usr/local/bin/python

exec setsid cttyhack /bin/sh
